doctrine:
    dbal:
        driver: pdo_mysql
        host: '172.28.1.1'
        port: '3306'
        dbname: 'prueba'
        user: 'root'
        password: '1234'
        unix_socket: /var/lib/mysql/mysql.sock
        server_version: '5.7'
        charset: UTF8


        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
